### ISSUE TITLE
new files, debounce

### ISSUE THREAD

**Issue by laggingreflex** [start-runner/watch#14]
`start-watch` currently doesn't trigger on newly created files, as it takes input from `start-files` which expands the initial glob into the file list at the very beginning of the task, so any new files (an deleted files) do not trigger the watch task. 

What do you think about passing the initial glob directly to `chokidar`? Or would this better be made into a different module like `watch-all` or something?

Another thing I wanted was a debounce functionality. I started writing a wrapper but was wondering whether I would need to make it for `start-watch` or `watch-all`? (or probably both in the latter case)

I also wanted to use [`debounce-queue`](https://github.com/laggingreflex/debounce-queue) module in the debounce task, which outputs a list of all files modified instead of just the last/first file that regular debounce function (lodah.debounce) output, which I think is a better approach in this scenario where all changed files matter. I'd love your thoughts on this aspect as well.

**Comment by deepsweet** [comment]
chokidar has `add` and `unlink` events, so yeah, probably I need to think about passing files glob as is bypassing start-files (but I need to check that they have similar glob posibilities to have same "API" across different tasks with globs).

regarding the debounce thing – I'll check it later in more details, but it seems like it should be `watch-all` or something. but I still can't get the idea.

**Comment by laggingreflex** [comment]
Sorry for the confusion, but `start-watch-all` was actually my suggestion that passes globs directly to `chokidar`, as a wrapper/alternative to `start-watch`, just in case I thought you might have wanted to keep it separate. 

Debounce is a separate thing. And since you're leaning towards adding this feature (pass globs to chokidar) in `start-watch` itself, I could probably just make `start-watch-debounce` (otherwise I'd have to make `start-watch-debounce`, *and* `start-watch-all-debounce`).

So anyways, back to chokidar/glob thing, currently the API is like this:
```
  files('src/server/**/*.js'),
  watch(file => start(
    files(file),
    read(),
    babel(),
```
If the globs were to be passed via watch to chokidar directly it might look like this:
```
  watch('src/server/**/*.js', file => start(
    files(file),
    read(),
    babel(),
```
which also eliminates the need for the initial `files` task. Thoughts?

The `unlink` event here might cause an issue. For eg. if `file` is actually the path of a deleted file then those subsequent tasks will fail/throw errors. 

How about if `watch` also accepted an `opts` object that takes something like an `on: ['add', 'change']` as events to attach to `chokidar`. The the user could choose not to listen to the 'unlink' event. 

The `opts` object could also be used to pass other options directly to `chokidar`, like `{cwd, ignore, ...}`

**Comment by laggingreflex** [comment]
#16 fixes this. Closing. Let me know when it's published.
